### PR TITLE
remove counterproductive aria-label

### LINKED ISSUE #600: Screen reader a11y: PublicationListElement wrong labels
The ARIA labels are announced for each paragraph, but this erases the actual values in each paragraph. ARIA labelled-by is probably more semantically correct, although this would require 

https://github.com/readium/readium-desktop/blob/41733d4b5ece3d1810f2972ae107c7b811c1c920/src/renderer/components/publication/PublicationListElement.tsx#L100

https://github.com/readium/readium-desktop/blob/41733d4b5ece3d1810f2972ae107c7b811c1c920/src/renderer/components/publication/PublicationListElement.tsx#L108

https://github.com/readium/readium-desktop/blob/41733d4b5ece3d1810f2972ae107c7b811c1c920/src/renderer/components/publication/PublicationListElement.tsx#L110

https://github.com/readium/readium-desktop/blob/41733d4b5ece3d1810f2972ae107c7b811c1c920/src/renderer/components/publication/PublicationListElement.tsx#L103

### PR DESCRIPTION
**Pull request by Scarsniik**
Fixes #600

### CODE REVIEW

File: src/typings/en.translation.d.ts [hunk 1]
```diff
@@ -11,10 +11,6 @@ declare namespace typed_i18n {
   readonly "searchBook": string,
   readonly "skipLink": string
 };
-  (_: "accessibility.bookAuthor", __?: {}): string;
-  (_: "accessibility.bookPublisher", __?: {}): string;
-  (_: "accessibility.bookReleaseDate", __?: {}): string;
-  (_: "accessibility.bookTitle", __?: {}): string;
```
Comment (danielweck) [inline src/typings/en.translation.d.ts]: I see that the `readonly "bookAuthor": string,` (etc.) lines are still present in this file, which indicates that this code removal was done manually. In order to maintain locales, I would strongly recommend using the automated scripts instead: `npm run i18n:typed` (the other commands perform other tasks `npm run i18n:sort` and `npm run i18n:scan`). See README:
https://github.com/readium/readium-desktop/blob/develop/README.md#localization--ui-translations

Comment (Scarsniik) [reply src/typings/en.translation.d.ts]: Oh, I didn't know there was a script, it's easier like that

**Comment by danielweck** [comment]
Thanks Leo, merging...
