### PR TITLE
[FIXES #849]

### LINKED ISSUE #849: REGRESSION BUG: catalog view: add/remove OPDS feed requires reloading the view to show changes (should be instant)
Bug introduced by https://github.com/readium/readium-desktop/commit/b745aab73773dfba643a23f58ca48083af74382c

`b745aab73773dfba643a23f58ca48083af74382c` (Nov 15, 2019)
https://github.com/readium/readium-desktop/commits/develop

### PR DESCRIPTION
**Pull request by panaC**
fixes #849

### CODE REVIEW

File: src/renderer/redux/reducers/api.ts [hunk 1]
```diff
@@ -60,18 +72,36 @@ export function apiReducer(
...
+            lastApiSuccess.lastSuccess = lastApiSuccess.data;
+            lastApiSuccess.lastTime = lastApiSuccess.data?.time || 0;
+            lastApiSuccess.data = returnState[requestId].data;
+
+            // no error is happened
+            // return all the API state and the lastApiSuccess dedicated channel
             return {
                 ...returnState,
-                [LAST_API_SUCCESS_ID]: returnState[requestId],
+                [LAST_API_SUCCESS_ID]: lastApiSuccess,
```
Comment (danielweck) [inline src/renderer/redux/reducers/api.ts]: I see, this is the most relevant code/logic change in this PR (the rest is comments and formatting, which are also useful).
I do not understand all the details, but I approve the PR.
