### PR TITLE
Fixes #660 reader paginated mode button

### LINKED ISSUE #660: Regression, impossible to change disposition / scrollable to paginated
On a reflow ebook, I open the ebook, open the tab controlling parameters / Display.
I'm in scrollable mode at this point. I select Paginated  (several times) -> no action.

Now I select Scrollable (which is the current mode) then Paginated -> it works.

### PR DESCRIPTION
**Pull request by Scarsniik**

### CODE REVIEW

File: src/renderer/components/reader/Reader.tsx [hunk 1]
```diff
@@ -670,6 +670,7 @@ export class Reader extends React.Component<ReaderProps, ReaderState> {
         settingsValues[name] =  value;
 
         this.setState({settingsValues});
+        console.log(name, givenValue, settingsValues);
```
Comment (panaC) [inline src/renderer/components/reader/Reader.tsx]: console.log :)

File: src/renderer/components/reader/ReaderOptions.tsx [hunk 2]
```diff
@@ -198,6 +198,7 @@ export class ReaderOptions extends React.Component<Props> {
 
     private displayContent() {
         const {__, settings} = this.props;
+        console.log(settings.paged);
```
Comment (panaC) [inline src/renderer/components/reader/ReaderOptions.tsx]: console.log :)
