### PR TITLE
Fix/get library focus back

### LINKED ISSUE #455: bookshelf view: after closing book info dialog, focus should return to calling site (menu item, or menu button)
ThoriumDialogKeyboardFocus

Related issue: https://github.com/readium/readium-desktop/issues/425

Also see (consistency between escape and click-cross): https://github.com/readium/readium-desktop/issues/349

### PR DESCRIPTION
**Pull request by manuellagrand**
This PR is about to give back focus to publication menu button when his modal window (publication informations window)  is closed.

fixes #455

### CODE REVIEW

File: src/renderer/components/dialog/Dialog.tsx [hunk 1]
```diff
@@ -72,6 +72,9 @@ export class Dialog extends React.Component<Props, undefined> {
                             title={__("dialog.closeModalWindow")}
                             data-dismiss="dialog"
                             onClick={this.props.close}
+                            onKeyPress={(e) => {
+                                if (e.charCode === 13) { this.props.close(); }
+                            }}
```
Comment (danielweck) [inline src/renderer/components/dialog/Dialog.tsx]: Please remove, already handled by `onClick`

File: src/renderer/components/utils/Slider.tsx [hunk 2]
```diff
@@ -124,12 +124,13 @@ export default class Slider extends React.Component<Props, State> {
...
-        if (!isVisible) {
-            elementPosition = elementPosition > 0 ? 0 : elementPosition < max ? max : elementPosition;
-            this.setState({position: elementPosition, refreshVisible: true});
+        if (element) {
+            let elementPosition = -element.offsetLeft;
+            const isVisible = this.isElementVisible(elementId);
+            if (!isVisible) {
+                elementPosition = elementPosition > 0 ? 0 : elementPosition < max ? max : elementPosition;
+                this.setState({position: elementPosition, refreshVisible: true});
+            }
```
Comment (danielweck) [inline src/renderer/components/utils/Slider.tsx]: Please remove this change and isolate the bug in the issue tracker. Thanks! :)

File: src/renderer/components/utils/Slider.tsx [hunk 3]
```diff
@@ -124,13 +124,12 @@ export default class Slider extends React.Component<Props, State> {
...
-            if (!isVisible) {
-                elementPosition = elementPosition > 0 ? 0 : elementPosition < max ? max : elementPosition;
-                this.setState({position: elementPosition, refreshVisible: true});
-            }
+
+        let elementPosition = -element.offsetLeft;
+        const isVisible = this.isElementVisible(elementId);
+        if (!isVisible) {
+            elementPosition = elementPosition > 0 ? 0 : elementPosition < max ? max : elementPosition;
+            this.setState({position: elementPosition, refreshVisible: true});
```
Comment (danielweck) [inline src/renderer/components/utils/Slider.tsx]: Hello @manuellagrand could you please file a new issue describing how to reproduce the bug you identified when you introduced this check for undefined/null/falsy `element`. Thank you!
