### PR TITLE
Fix/drag and drop

### LINKED ISSUE #426: Drag and drop from filesystem: should only accept recognized file types (EPUB, OPDS, LCPL)
Here is what happens when a PNG image file is drag+dropped onto the library view:

ThoriumFileDrop

Code reference:
https://github.com/readium/readium-desktop/blob/541e48bbe45407a8918018e0076d4ca5ebecd68b/src/renderer/components/App.tsx#L52-L65

### PR DESCRIPTION
**Pull request by manuellagrand**
This PR fix drag and drop issue and prevent to the add of file with the wrong extension

fixes #426

### CODE REVIEW

File: src/renderer/components/App.tsx [hunk 1]
```diff
@@ -64,6 +66,19 @@ export default class App extends React.Component<any, undefined> {
         ));
     }
 
+    public cleanTabFile(files: File[]): File[] {
+        const tab: File[] = [];
+
+        files.map((file) => {
+            if (file.name.search(".epub") !== -1 ||
+                file.name.search(".opds") !== -1 ||
+                file.name.search(".lcpl") !== -1) {
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: Please use `path.extname()` https://nodejs.org/api/path.html#path_path_extname_path

File: src/renderer/components/App.tsx [hunk 2]
```diff
@@ -64,6 +66,19 @@ export default class App extends React.Component<any, undefined> {
         ));
     }
 
+    public cleanTabFile(files: File[]): File[] {
+        const tab: File[] = [];
+
+        files.map((file) => {
+            if (file.name.search(".epub") !== -1 ||
+                file.name.search(".opds") !== -1 ||
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: 1) Note that OPDS feeds do not necessarily end with the `.opds` file extension. For example: https://www.feedbooks.com/catalog.atom
2) I do not think OPDS feeds can be drag-dropped onto the Thorium UI anyway, see error:
```
[2]   readium-desktop:main#redux/sagas/api TypeError: Cannot read property 'resources' of null
[2]   readium-desktop:main#redux/sagas/api     at PublicationViewConverter.convertDocumentToView (/Volumes/500GB/Code/readium-desktop/dist/main.js:2891:47)
[2]   readium-desktop:main#redux/sagas/api     at newDocs.map (/Volumes/500GB/Code/readium-desktop/dist/main.js:2494:67)
[2]   readium-desktop:main#redux/sagas/api     at Array.map (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at PublicationApi.<anonymous> (/Volumes/500GB/Code/readium-desktop/dist/main.js:2493:28)
[2]   readium-desktop:main#redux/sagas/api     at Generator.next (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at fulfilled (/Volumes/500GB/Code/readium-desktop/dist/main.js:2400:58)
[2]   readium-desktop:main#redux/sagas/api     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```

File: src/renderer/components/dialog/FileImport.tsx [hunk 3]
```diff
@@ -31,41 +31,46 @@ export class FileImport extends React.Component<FileImportProps, undefined> {
...
+            const paths = this.props.files.map((file: File) => {
+                return file.path;
+            });
+            this.props.importFiles({ paths });
+            this.props.closeDialog();
+        }
     }
 
-    private buildBasicFileImportList() {
+    private buildBasicFileImportList(__: any) {
```
Comment (danielweck) [inline src/renderer/components/dialog/FileImport.tsx]: No need to add the function parameter `__: any`, as you can see inside the function body there is already usage of `this.props.__`.

File: src/renderer/components/App.tsx [hunk 4]
```diff
@@ -50,11 +50,13 @@ export default class App extends React.Component<any, undefined> {
 
     // Called when files are droped on the dropzone
     public onDrop(acceptedFiles: File[]) {
+        const tabfile: File[] = this.cleanTabFile(acceptedFiles);
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: Just out of interest, why the term "tab"? (sorry if I am missing something obvious ;)

File: src/renderer/components/App.tsx [hunk 5]
```diff
@@ -64,6 +66,19 @@ export default class App extends React.Component<any, undefined> {
         ));
     }
 
+    public cleanTabFile(files: File[]): File[] {
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: Coding advice: rather than "clean", use a more self-explanatory term such as "filterImportFilesByAllowedExtensions" (this is just an example, feel free to adapt :)

File: src/renderer/components/App.tsx [hunk 6]
```diff
@@ -64,6 +66,19 @@ export default class App extends React.Component<any, undefined> {
...
+        const tab: File[] = [];
+
+        files.map((file) => {
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: Do not use `Array.map()` if the code does not use the return value of the function call. Instead, iterate the list of files using `Array.forEach()` or `for (const item of array) { ... }`.

File: src/resources/locales/fr.json [hunk 7]
```diff
@@ -108,6 +108,7 @@
     "available": "Nouvelle version !"
   },
   "dialog": {
+    "importError": "une erreur s'est produite, vérifiez l'extension de votre fichier (.epub,.opds ou.lcpl)",
```
Comment (danielweck) [inline src/resources/locales/fr.json]: Space characters missing in `.epub,.opds ou.lcpl`

File: src/resources/locales/de.json [hunk 8]
```diff
@@ -81,6 +81,7 @@
         "available": "Update verfügbar!"
     },
     "dialog": {
+      "importError": "ein Fehler ist aufgetreten, überprüfen Sie Ihre Dateiendung (.epub,.opds oder.lcpl).",
```
Comment (danielweck) [inline src/resources/locales/de.json]: Spaces missing in `.epub,.opds oder.lcpl`

File: src/renderer/components/App.tsx [hunk 9]
```diff
@@ -50,11 +50,13 @@ export default class App extends React.Component<any, undefined> {
...
     // Called when files are droped on the dropzone
     public onDrop(acceptedFiles: File[]) {
+        const tabfile: File[] = this.cleanTabFile(acceptedFiles);
+
         this.store.dispatch(
             dialogActions.open(
                 DialogType.FileImport,
                 {
-                    files: acceptedFiles.map((file) => {
+                    files: tabfile.map((file) => {
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: This is a minor coding remark: instead of introducing a new function `cleanTabFile()`to filter out some values from the original array of dropped files, you could simply use the `Array.filter()` function with a simple function predicate that excludes non-recognized file extensions, and chain the result (`acceptedFiles.filter(...).map(...)`). See:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

File: src/renderer/components/App.tsx (hunk 4 above)
Comment (manuellagrand) [reply src/renderer/components/App.tsx]: tabfile is for table of file. i can change this variable name if it isn't enough relevant.

Comment (danielweck) [reply src/renderer/components/App.tsx]: You mean an "array" / "list"?
In English, a "table" is a matrix (or something you have dinner at ;)

Comment (danielweck) [reply src/renderer/components/App.tsx]: 2D matrix = rows+columns

File: src/renderer/components/App.tsx [hunk 10]
```diff
@@ -105,7 +112,7 @@ export default class App extends React.Component<any, undefined> {
                         </Dropzone>
                     </div>
                 </ConnectedRouter>
-            </Provider>
+            </Provider >
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: Minor: is this space character intentional?

File: src/renderer/components/App.tsx [hunk 11]
```diff
@@ -54,7 +57,11 @@ export default class App extends React.Component<any, undefined> {
             dialogActions.open(
                 DialogType.FileImport,
                 {
-                    files: acceptedFiles.map((file) => {
+                    files: acceptedFiles.filter((file) => {
+                            return (path.extname(file.path) === ".epub" ||
+                            path.extname(file.path) === ".lcpl");
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: Once last nit-picking comment :)

`path.extname(file.path)` is evaluated twice at each iteration. Instead, just store the string value in a constant variable scoped to the function body:

```javascript
files: acceptedFiles.filter((file) => {
    const ext = path.extname(file.path);
    return (ext === ".epub" || ext === ".lcpl");
}
```
