### PR TITLE
[READY] centralization of the starting point for reader and main app

### LINKED ISSUE #882: When changing language, tab headers only refresh when switching tab (regression)
I think this is a regression from this PR:
https://github.com/readium/readium-desktop/pull/879/files#diff-a1228900df8ff573cefb675232bfceb2
(not 100% sure, but the `__` translate props looks suspicious)

### PR DESCRIPTION
**Pull request by panaC**
fixes #882 #897

### CODE REVIEW

File: src/common/services/translator.ts [hunk 1]
```diff
@@ -132,6 +132,10 @@ export class Translator {
     public translate: I18nTyped = this._translate;
     private locale: string = "en";
 
+    constructor(defaultLocale = "en") {
```
Comment (danielweck) [inline src/common/services/translator.ts]: Is this change necessary? The Dependency Injection Container will not automatically create a `Translator` instance with a constructor parameter, so this would need to be an explicit `new Translator("fr")` (for example) from `di.ts` ... but this is currently not the case:

https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/di.ts#L167

File: src/renderer/components/App.tsx [hunk 2]
```diff
@@ -18,23 +17,13 @@ import * as dialogActions from "readium-desktop/common/redux/actions/dialog";
...
 import DownloadsPanel from "./DownloadsPanel";
 import ToastManager from "./toast/ToastManager";
 
 export default class App extends React.Component<{}, undefined> {
 
-    @lazyInject(diRendererSymbolTable.store)
-    private store: Store<RootState>;
-
-    @lazyInject(diRendererSymbolTable.history)
-    private history: History<IRouterLocationState>;
```
Comment (danielweck) [inline src/renderer/components/App.tsx]: This change is interesting. Are you recommending removing *all* occurrences of `@lazyInject` in the renderer process code? (and instead replace with `diRendererGet("xx")` wherever required?) Do you think `@lazyInject` is unreliable, or is this change motivated by personal coding taste?

File: src/common/services/translator.ts (hunk 1 above)
Comment (panaC) [reply src/common/services/translator.ts]: you're right c2ca422276e16d13109655e3cec416cacbad3969

File: src/renderer/redux/sagas/win.ts [hunk 3]
```diff
@@ -5,14 +5,55 @@
...
+
         yield put(winActions.initSuccess.build());
     }
 }
+
+let notRendered = true;
+
+function* winStartWatcher(): SagaIterator {
+
+    while (true) {
```
[the remark this answers is not in the document]
Comment (panaC) [reply src/renderer/redux/sagas/win.ts]: you're right 1730aa3f473e58fb3eebc7d928d7d9b2d22e00e4

File: src/renderer/redux/sagas/i18n.ts [hunk 4]
```diff
@@ -13,8 +13,11 @@ import { all, call } from "redux-saga/effects";
 function* localeWatcher() {
     while (true) {
         const action = yield* takeTyped(i18nActions.setLocale.build);
+
         const translator = diRendererGet("translator");
         translator.setLocale(action.payload.locale);
+
+        document.documentElement.setAttribute("lang", action.payload.locale);
```
[the remark this answers is not in the document]
Comment (panaC) [reply src/renderer/redux/sagas/i18n.ts]: ok

File: src/renderer/components/reader/Reader.tsx [hunk 5]
```diff
@@ -76,10 +74,7 @@ import optionsValues, {
 //     supportFetchAPI: true,
 // });
 
-/**
- * WHY lot of const variable not in constructor ?
- */
-const queryParams = getURLQueryParams();
+const queryParams = () => getURLQueryParams();
```
[the remark this answers is not in the document]
Comment (panaC) [reply src/renderer/components/reader/Reader.tsx]: yes , it's necessary when imported from redux-saga `win.ts`.
What is your proposal ?

File: src/renderer/components/App.tsx (hunk 2 above)
Comment (panaC) [reply src/renderer/components/App.tsx]: `lazyInject` causes problems when importing from redux-saga

Comment (danielweck) [reply src/renderer/components/App.tsx]: Ok, so this PR removes all usages of `@lazyInject`.

File: src/renderer/components/reader/Reader.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (danielweck) [reply src/renderer/components/reader/Reader.tsx]: Related issue: https://github.com/readium/readium-desktop/issues/554

[the remark this answers is not in the document]
Comment (danielweck) [reply src/renderer/components/reader/Reader.tsx]: `window.location.search` should be "statically" / "immediately" available to the `BrowserWindow`'s URL, see:
https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/redux/sagas/reader.ts#L130-L149

[the remark this answers is not in the document]
Comment (panaC) [reply src/renderer/components/reader/Reader.tsx]: resolved by technical call

File: src/renderer/components/reader/Reader.tsx [hunk 6]
```diff
@@ -145,19 +138,22 @@ const computeReadiumCssJsonMessage = (): IEventPayload_R2_EVENT_READIUMCSS => {
...
 };
-setReadiumCssJsonGetter(computeReadiumCssJsonMessage);
 
-const publicationJsonUrl = queryParams.pub.startsWith(READIUM2_ELECTRON_HTTP_PROTOCOL) ?
-    convertCustomSchemeToHttpUrl(queryParams.pub) : queryParams.pub;
+const queryParams = getURLQueryParams();
+const lcpHint = queryParams.lcpHint;
+// pub is undefined when loaded in dependency injection by library webview.
+// Dependency injection is shared between all the renderer view
+const publicationJsonUrl = queryParams.pub?.startsWith(READIUM2_ELECTRON_HTTP_PROTOCOL)
```
Comment (danielweck) [inline src/renderer/components/reader/Reader.tsx]: Is the question mark `?` and the code comment necessary here? If I am not mistaken, the URL query parameter `pub` is available immediately and reliably in the `BrowserWindow` / `webContents` URL:

https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/redux/sagas/reader.ts#L130-L149

Comment (panaC) [reply src/renderer/components/reader/Reader.tsx]: no, it's always necessary here, the Reader code is imported in DI. And the DI is shared between reader and library. I am working to improve that in the future PR

File: src/renderer/di.ts [hunk 7]
```diff
@@ -16,6 +16,9 @@ import { diRendererSymbolTable as diSymbolTable } from "readium-desktop/renderer
 import { RootState } from "readium-desktop/renderer/redux/states";
 import { initStore } from "readium-desktop/renderer/redux/store/memory";
 import { Store } from "redux";
+
+import * as mainApp from "./components/App";
+import * as readerApp from "./components/reader/App";
```
Comment (danielweck) [inline src/renderer/di.ts]: I would like to suggest changing this to a cleaner syntax:
`import MainApp from "./components/App";`

...and simply use `MainApp` instead of `mainApp.default` in the code below.

File: src/renderer/components/reader/Reader.tsx (hunk 6 above)
Comment (danielweck) [reply src/renderer/components/reader/Reader.tsx]: Ah yes of course, WebPack's statically-created bundle (at build time) imports the entire code hierarchy  ... so we need a separate PR to split the reader / library scopes.

File: src/renderer/di.ts (hunk 7 above)
Comment (panaC) [reply src/renderer/di.ts]: 1e07d8e9

**Comment by danielweck** [comment]
Note that this PR messes-up the reader/library CSS due to combining both scopes into the same WebPack bundle. This is because we are staging multiple consecutive (small) PRs in order to solve the bigger issues, incrementally. So the develop branch currently runs but has some rendering bugs.
